apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: shop
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          # on-prem
          - name: shop-onprem
            server: https://kubernetes.default.svc
            path: k8s/overlays/onprem

          # EKS
          - name: shop-eks
            server: https://F70628B4EB910B9F45BF46A3DAB07A3.gr7.ap-northeast-2.eks.amazonaws.com
            path: k8s/overlays/eks

  template:
    metadata:
      name: "{{name}}"
      labels:
        app: shop
        managed-by: applicationset
    spec:
      project: default

      source:
        repoURL: https://github.com/jwahn2018-rgb/5x5y-shop
        targetRevision: gill-test
        path: "{{path}}"

      destination:
        server: "{{server}}"
        namespace: shop

      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true

