apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: shopping-mall
  namespace: argocd
spec:
  project: default
  
  source:
    repoURL: https://github.com/your-username/your-repo.git
    targetRevision: main
    path: k8s
  
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
  
  revisionHistoryLimit: 3

