apiVersion: v1
kind: ServiceAccount
metadata:
  name: shop-serviceaccount
  namespace: shop
  annotations:
    # EKS IRSA annotation (EKS overlay에서 덮어쓰기)
    eks.amazonaws.com/role-arn: ""  # EKS overlay에서 설정
